apiVersion: apps/v1
kind: ReplicaSet
  name: app-js-replicaset
  namespace: app-js
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-js
  template:
    metadata:
      labels:
        app: app-js
    spec:
      containers:
      - name: app-js
        image: julianaguirre22/app_js:1.0

        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://mongodb:27017/"