apiVersion: v1
kind: Service
metadata:
  name: app-js-service
  namespace: app-js
spec:
  selector:
    app: app-js
  ports:
  - name: http
    port: 3000
    targetPort: 3000
  type: LoadBalancer
