apiVersion: v1
kind: Pod
metadata:
  name: app-js
spec:
  containers:
  - name: app-js
    image: julianaguirre22/app_nodejs:2.0
    ports:
    - containerPort: 3000
    env:
    - name: MONGO_URI
      value: "mongodb://mongodb:27017/"