apiVersion: v1
kind: Service
metadata:
  name: mongo-express-service
  namespace: app-js
spec:
  selector:
    app: mongo-express
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  type: LoadBalancer
