apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-js-deployment
  namespace: app-js
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-js
  template:
    metadata:
      labels:
        app: app-js
    spec:
      containers:
        - name: app-js
          image: 431317130650.dkr.ecr.us-east-1.amazonaws.com/app_nodejs:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongodb:27017/"
